spring:
  application:
    name: sistema-de-gerenciamento-de-estoque

  rsocket:
    server:
      port: 5050

  datasource:
    url: jdbc:postgresql://db-sgde:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true



