spring:
  application:
    name: sistema-de-gerenciamento-de-estoque

  datasource:
    url: jdbc:postgresql://localhost:5051/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true


  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:5052/realms/${KEYCLOAK_REALM}
  rsocket:
    server:
      port: 5050



